name: Ben Snodin
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima

collections:
  research_articles:

plugins:
  - jekyll-seo-tag
  - jekyll-feed

kramdown:
  auto_ids: true
